### ISSUE TITLE
No puedo agregar estudiante. Tira error

### ISSUE THREAD

**Issue by estebancalabria** [daxcurson/gamification#17]
Estado HTTP 500 - Request processing failed; nested exception is org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement

**Comment by daxcurson** [comment]
No se puede reproducir este error. Agregar y editar funcionan perfectamente.
